source "https://rubygems.org"

gem "jekyll", "3.8.6"
gem "html-proofer"
gem "rb-fsevent", "0.9.8"

group :jekyll_plugins do
      gem 'jekyll-livereload'

gem 'jekyll-compose', group: [:jekyll_plugins]
end
